baseURL = 'http://doifoundation-wsl.com'
#baseURL = 'https://staging.doi.com'
languageCode = 'en-us'
title = 'DOI Foundation WIP site'
theme = "doi-theme"

[markup.goldmark.renderer]
unsafe= true


[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]


[[deployment.targets]]
name = "s3_staging"
URL = "s3://staging.doi.org?region=us-west-2"

[[deployment.targets]]
# An arbitrary name for this target.
name = "s3_live"
URL = "s3://www-new.doi.org?region=us-west-2"


# [[deployment.matchers]] configure behavior for files that match the Pattern.
# See https://golang.org/pkg/regexp/syntax/ for pattern syntax.
# Pattern searching is stopped on first match.

# Samples:

[[deployment.matchers]]
# Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
# Set custom content type for /sitemap.xml
pattern = "^sitemap\\.xml$"
contentType = "application/xml"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true


[menu]
[[menu.main]]
  name = 'The Foundation'
  url = '/the-foundation/'
  weight = 1
  identifier = 'foundation'
[[menu.main]]
  name = 'Sub Menu2'
  url = '/submenu2/'
  weight = 4
  identifier = 'submenu2'
  parent = 'foundation'
[[menu.main]]
  name = 'Sub Menu3'
  url = '/submenu3/'
  weight = 4
  identifier = 'submenu3'
  parent = 'foundation'
[[menu.main]]
  name = 'Sub Menu4'
  url = '/submenu4/'
  weight = 4
  identifier = 'submenu4'
  parent = 'foundation'
[[menu.main]]
  name = 'Sub Menu5'
  url = '/submenu5/'
  weight = 4
  identifier = 'submenu5'
  parent = 'foundation'


[[menu.main]]
  name = 'The Community'
  url = '/the-community/'
  weight = 2
  identifier = 'community'
[[menu.main]]
  name = 'The Identifier'
  url = '/the-identifier/'
  weight = 3
  identifier = 'identifier'

[[menu.main]]
  name = 'Resources'
  url = '/resources/'
  weight = 4
  identifier = 'resources'
[[menu.main]]
  name = 'Sub Menu'
  url = '/submenu/'
  weight = 4
  identifier = 'submenu'
  parent = 'resources'
[[menu.main]]
  name = 'Sub Menu1'
  url = '/submenu1/'
  weight = 4
  identifier = 'submenu1'
  parent = 'resources'
