baseURL = 'http://doifoundation-wsl.com'
#baseURL = 'https://staging.doi.com'
languageCode = 'en-us'
title = 'DOI Foundation WIP site'
theme = "doi-theme"

[markup.goldmark.renderer]
unsafe= true


[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]


[[deployment.targets]]
name = "s3_staging"
URL = "s3://staging.doi.org?region=us-west-2"

[[deployment.targets]]
# An arbitrary name for this target.
name = "s3_live"
URL = "s3://www-doi-org?region=us-west-2"


# [[deployment.matchers]] configure behavior for files that match the Pattern.
# See https://golang.org/pkg/regexp/syntax/ for pattern syntax.
# Pattern searching is stopped on first match.

# Samples:

[[deployment.matchers]]
# Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
# Set custom content type for /sitemap.xml
pattern = "^sitemap\\.xml$"
contentType = "application/xml"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true


[menu]
[[menu.main]]
  name = 'The Foundation'
  url = '/the-foundation/'
  weight = 1
  identifier = 'foundation'
  [menu.main.params]
    nolink = true
[[menu.main]]
  name = 'Governance & Sustainability'
  url = '/the-foundation/governance-and-sustainability/'
  weight = 4
  identifier = 'submenu2'
  parent = 'foundation'
  
[[menu.main]]
  name = 'The Community'
  url = '/the-community/'
  weight = 2
  identifier = 'community'
  [menu.main.params]
  nolink = true
[[menu.main]]
  name = 'What are Registration Agencies'
  url = '/the-community/what-are-registration-agencies/'
  weight = 3
  identifier = 'whatare'
  parent = 'community'
[[menu.main]]
  name = 'Existing Registration Agencies'
  url = '/the-community/existing-registration-agencies/'
  weight = 4
  identifier = 'whatare2'
  parent = 'community'
[[menu.main]]
  name = 'Who Are The Members'
  url = '/the-community/who-are-the-members/'
  weight = 5
  identifier = 'whoare'
  parent = 'community'

[[menu.main]]
  name = 'The Identifier'
  url = '/the-identifier/'
  weight = 3
  identifier = 'identifier'
  [menu.main.params]
    nolink = true
[[menu.main]]
  name = 'What is a DOI'
  url = '/the-identifier/what-is-a-doi/'
  weight = 4
  identifier = 'whatisadoi'
  parent = 'identifier'

[[menu.main]]
  name = 'Resources'
  url = '/resources/'
  weight = 4
  identifier = 'resources'
