name: Build and Deploy

on: push

jobs:
  stagingbuild:
    name: Staging Build and Deploy
    runs-on: ubuntu-latest
    
    if: github.ref_name == 'staging'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Hugo Setup
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.137.0'
          extended: true
      - name: Hugo Build
        run: hugo --baseURL "https://staging.doi.org/"
      - name: Deploy to S3
        if: github.ref_name == 'staging'
        run: hugo deploy --target=s3_staging --maxDeletes -1 --force
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    
  livebuild:
    name: Live Build and Deploy
    runs-on: ubuntu-latest

    if: github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Hugo Setup
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.101.0'
          extended: true
      - name: Hugo Build
        run: hugo -v --baseURL "https://www.doi.org/"
      - name: Deploy to S3
        if: github.ref_name == 'main'
        run: hugo  -v deploy --target=s3_live --maxDeletes -1 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
