name: Build and Deploy

on: push

jobs:
  stagingbuild:
    name: Staging Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Hugo
        run: |
          HUGO_DOWNLOAD=hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_DOWNLOAD}
          tar xvzf ${HUGO_DOWNLOAD} hugo
          mv hugo $HOME/hugo
        env:
          HUGO_VERSION: 0.99.1
      - name: Hugo Build
        run: $HOME/hugo -v --baseURL "https://staging.doi.org/"
      - name: Deploy to S3
        run: $HOME/hugo -v deploy --target=s3_staging --maxDeletes -1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    
  livebuild:
    name: Live Build and Deploy
    runs-on: ubuntu-latest
    needs: stagingbuild
    if: github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v2
      - name: Install Hugo
        run: |
          HUGO_DOWNLOAD=hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_DOWNLOAD}
          tar xvzf ${HUGO_DOWNLOAD} hugo
          mv hugo $HOME/hugo
        env:
          HUGO_VERSION: 0.99.1
      - name: Hugo Build
        run: $HOME/hugo -v --baseURL "https://www-new.doi.org/"
      - name: Deploy to S3
        if: github.ref_name == 'main'
        run: $HOME/hugo  -v deploy --target=s3_live --maxDeletes -1 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
